"""DB settings changed

Revision ID: 9020e9c99fff
Revises: cdaae99e3c42
Create Date: 2025-01-10 22:06:16.200874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9020e9c99fff'
down_revision: Union[str, None] = 'cdaae99e3c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
