version: "3.8"

services:
  app:
    build: .
    container_name: bar_inventory_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - bar_inventory_network
    ports:
      - "8000:8000"

  db:
    image: postgres:alpine
    container_name: bar_inventory_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_LOGGING_COLLECTOR: "on"
      POSTGRES_LOG_FILE: "/var/log/postgresql/postgresql.log"
    ports:
      - "5433:5432" # Проброс порта на локальной машине 5433, а внутри контейнера останется 5432
    networks:
      - bar_inventory_network
    volumes:
      - db_data:/var/lib/postgresql/data
    mem_limit: 512m

networks:
  bar_inventory_network:
    driver: bridge

volumes:
  db_data:

