version: '3.8'

services:
  app:
    build:
      context: .
    container_name: bar_inventory_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PYTHONWARNINGS=ignore
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 2g

  db:
    image: postgres:15
    container_name: bar_inventory_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: